# Generated by Django 5.2.3 on 2026-03-27 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("business", "0002_business_is_active_business_views_count_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="is_replied",
            field=models.BooleanField(default=False),
        ),
    ]
