# Generated by Django 6.0.2 on 2026-02-26 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='firstName',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='lasttName',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
