# Generated by Django 6.0.2 on 2026-02-26 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_user_firstname_alter_user_lasttname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('owner', 'Business Owner'), ('event_organizer', 'Event Organizer'), ('user', 'Community Member')], default='user', max_length=20),
        ),
    ]
