# Generated by Django 6.0.2 on 2026-03-23 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_contact"),
    ]

    operations = [
        migrations.AddField(
            model_name="contact",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
